from __future__ import annotations

import os
import re
from pathlib import Path

HOOK_MARKER_START = "# >>> LarkMemory hook >>>"
HOOK_MARKER_END = "# <<< LarkMemory hook <<<"

_BASH_HOOK_TEMPLATE = r"""# >>> LarkMemory hook >>>
# LarkMemory CLI workflow memory - shell hooks
# Generated by: lark-memory hook install
# Do not edit this block manually.

_lark_preexec() {
    local _cmd="$1"
    case "$_cmd" in
        "lark-memory"*|"_lark_"*|"")
            return
            ;;
    esac
    _LARK_LAST_CMD="$_cmd"
    _LARK_CMD_START=$(date +%s%3N 2>/dev/null || echo 0)
}

_lark_precmd() {
    local _exit=$?
    [ -z "$_LARK_LAST_CMD" ] && return
    local _duration=0
    [ "$_LARK_CMD_START" != "0" ] && _duration=$(( $(date +%s%3N 2>/dev/null || echo 0) - _LARK_CMD_START ))
    (lark-memory ingest --command "$_LARK_LAST_CMD" --exit-code $_exit --cwd "$PWD" --duration $_duration </dev/null >/dev/null 2>&1 &)
    _LARK_LAST_CMD=""
}

_lark_memory_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local line="${COMP_LINE}"
    local result
    result=$(lark-memory complete -- "$line" "$cur" 2>/dev/null)
    if [ -n "$result" ]; then
        local IFS=$'\n'
        COMPREPLY=($(compgen -W "$result" -- "$cur"))
    fi
    return 0
}

trap '_lark_preexec "$BASH_COMMAND"' DEBUG

if [ -z "${PROMPT_COMMAND-}" ]; then
    PROMPT_COMMAND="_lark_precmd"
else
    case "$PROMPT_COMMAND" in
        *_lark_precmd*) ;;
        *) PROMPT_COMMAND="_lark_precmd;${PROMPT_COMMAND}" ;;
    esac
fi

complete -D -F _lark_memory_complete -o default 2>/dev/null || true
# <<< LarkMemory hook <<<
"""

_ZSH_HOOK_TEMPLATE = r"""# >>> LarkMemory hook >>>
# LarkMemory CLI workflow memory - shell hooks
# Generated by: lark-memory hook install
# Do not edit this block manually.

_lark_preexec() {
    local _cmd="$1"
    case "$_cmd" in
        "lark-memory"*|"_lark_"*|"")
            return
            ;;
    esac
    _LARK_LAST_CMD="$_cmd"
    _LARK_CMD_START=$(date +%s%3N 2>/dev/null || echo 0)
}

_lark_precmd() {
    local _exit=$?
    [ -z "$_LARK_LAST_CMD" ] && return
    local _duration=0
    [ "$_LARK_CMD_START" != "0" ] && _duration=$(( $(date +%s%3N 2>/dev/null || echo 0) - _LARK_CMD_START ))
    (lark-memory ingest --command "$_LARK_LAST_CMD" --exit-code $_exit --cwd "$PWD" --duration $_duration </dev/null >/dev/null 2>&1 &)
    _LARK_LAST_CMD=""
}

_lark_memory_complete_zsh() {
    local line="${BUFFER}"
    local cur="${words[$CURRENT]}"
    local result
    result=$(lark-memory complete -- "$line" "$cur" 2>/dev/null)
    if [ -n "$result" ]; then
        local -a candidates
        candidates=("${(@f)result}")
        compadd -a -- candidates
    fi
    return 0
}

_lark_memory_complete_wrapper() {
    _lark_memory_complete_zsh
}

autoload -Uz add-zsh-hook 2>/dev/null
if command -v add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook preexec _lark_preexec
    add-zsh-hook precmd _lark_precmd
fi

compdef _lark_memory_complete_wrapper '*' 2>/dev/null || true
# <<< LarkMemory hook <<<
"""

_MARKER_PATTERN = re.compile(
    rf"{re.escape(HOOK_MARKER_START)}.*?{re.escape(HOOK_MARKER_END)}",
    re.DOTALL,
)


def detect_shell() -> str:
    shell_path = os.environ.get("SHELL", "")
    shell_name = os.path.basename(shell_path).lower()
    if shell_name in ("zsh",):
        return "zsh"
    if os.environ.get("ZSH_VERSION"):
        return "zsh"
    return "bash"


def get_config_path(shell: str | None = None) -> Path:
    if shell is None:
        shell = detect_shell()
    home = Path.home()
    if shell == "zsh":
        rc_file = os.environ.get("ZDOTDIR", str(home))
        return Path(rc_file) / ".zshrc"
    return home / ".bashrc"


def get_hook_template(shell: str | None = None) -> str:
    if shell is None:
        shell = detect_shell()
    if shell == "zsh":
        return _ZSH_HOOK_TEMPLATE
    return _BASH_HOOK_TEMPLATE


_AUTOSUGGEST_MARKER = "# >>> LarkMemory autosuggest >>>"

_INPUTRC_SETTINGS = """# >>> LarkMemory inputrc >>>
# LarkMemory - enhanced Tab completion for bash
set show-all-if-ambiguous on
set colored-stats on
set completion-query-items 0
# <<< LarkMemory inputrc <<<
"""


def _install_autosuggest_strategy(shell: str) -> str | None:
    """Install zsh-autosuggestions strategy file. Returns path if installed."""
    home = Path.home()
    strategy_dir = home / ".larkmemory"
    strategy_dir.mkdir(parents=True, exist_ok=True)
    strategy_file = strategy_dir / "zsh-autosuggest-strategy.zsh"

    from src.sources.cli.completion import get_autosuggestion_strategy
    strategy_file.write_text(get_autosuggestion_strategy(), encoding="utf-8")
    return str(strategy_file)


def _optimize_inputrc(inputrc_path: str | None = None) -> str | None:
    """Append readline optimizations to ~/.inputrc. Returns path if written."""
    inputrc = Path(inputrc_path) if inputrc_path else Path.home() / ".inputrc"
    try:
        existing = inputrc.read_text(encoding="utf-8") if inputrc.exists() else ""

        if _AUTOSUGGEST_MARKER in existing:
            return None  # Already installed, skip

        new_content = existing.rstrip("\n") + "\n\n" + _INPUTRC_SETTINGS
        inputrc.write_text(new_content.lstrip("\n") + "\n", encoding="utf-8")
        return str(inputrc)
    except Exception:
        return None  # .inputrc write failure should not block hook install


def install(shell: str | None = None) -> tuple[bool, str]:
    if shell is None:
        shell = detect_shell()
    config_path = get_config_path(shell)
    hook_content = get_hook_template(shell)

    if not config_path.exists():
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.touch()

    existing = config_path.read_text(encoding="utf-8")

    if HOOK_MARKER_START in existing and HOOK_MARKER_END in existing:
        existing = _MARKER_PATTERN.sub("", existing).rstrip("\n") + "\n"

    new_content = (existing.rstrip("\n") + "\n\n" + hook_content).lstrip("\n")
    config_path.write_text(new_content + "\n", encoding="utf-8")

    extras: list[str] = []

    # zsh: install autosuggestion strategy
    if shell == "zsh":
        strategy_path = _install_autosuggest_strategy(shell)
        if strategy_path:
            extras.append(f"autosuggest strategy → {strategy_path}")

    # bash: optimize ~/.inputrc for Tab completion (best-effort)
    if shell == "bash":
        try:
            inputrc_path = _optimize_inputrc()
            if inputrc_path:
                extras.append(f"inputrc optimized → {inputrc_path}")
        except Exception:
            pass  # .inputrc failure does not block hook install

    msg = f"hook installed for {shell} → {config_path}"
    if extras:
        msg += "\n" + "\n".join(extras)
    return True, msg


def uninstall(shell: str | None = None) -> tuple[bool, str]:
    if shell is None:
        shell = detect_shell()
    config_path = get_config_path(shell)

    if not config_path.exists():
        return True, f"config not found: {config_path}"

    existing = config_path.read_text(encoding="utf-8")

    if HOOK_MARKER_START not in existing:
        return True, f"hook block not found in {config_path}"

    cleaned = _MARKER_PATTERN.sub("", existing)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).rstrip("\n")
    config_path.write_text(cleaned + "\n", encoding="utf-8")

    # Clean up autosuggest strategy file
    strategy_dir = Path.home() / ".larkmemory"
    strategy_file = strategy_dir / "zsh-autosuggest-strategy.zsh"
    if strategy_file.exists():
        strategy_file.unlink()
        try:
            remaining = list(strategy_dir.iterdir())
            if not remaining:
                strategy_dir.rmdir()
        except OSError:
            pass

    # Clean up inputrc
    inputrc = Path.home() / ".inputrc"
    if inputrc.exists():
        content = inputrc.read_text(encoding="utf-8")
        if _AUTOSUGGEST_MARKER in content:
            cleaned_rc = re.sub(
                rf"{re.escape(_AUTOSUGGEST_MARKER)}\n.*?{re.escape(HOOK_MARKER_END)}",
                "",
                content,
                flags=re.DOTALL,
            )
            cleaned_rc = re.sub(r"\n{3,}", "\n\n", cleaned_rc).rstrip("\n")
            if cleaned_rc.strip():
                inputrc.write_text(cleaned_rc + "\n", encoding="utf-8")
            else:
                inputrc.unlink(missing_ok=True)

    return True, f"hook uninstalled from {config_path}"


def is_installed(shell: str | None = None) -> bool:
    if shell is None:
        shell = detect_shell()
    config_path = get_config_path(shell)
    if not config_path.exists():
        return False
    content = config_path.read_text(encoding="utf-8")
    return HOOK_MARKER_START in content and HOOK_MARKER_END in content
